INTERNAL FIX: msm: ipa: don't depend on compiler constant propagation
Currently field_gen() and field_val() are inline functions. They
both use __builtin_constant_p() in compile-time asserts to verify the
const-ness of a function parameter. Building the driver/kernel with
clang fails, due to differences in constant propagation between clang
and gcc (clang doesn't consider a non-constant function parameter of
an inline function constant):

  drivers/net/ipa/gsi.o: In function `field_val':
  drivers/net/ipa/ipa_common_i.h:43: undefined reference to
    `__compiletime_assert_43'
  drivers/net/ipa/ipa_common_i.h:43:(.text+0x1d0): relocation truncated
    to fit: R_AARCH64_CALL26 against undefined symbol
    `__compiletime_assert_43'

more info: https://crbug.com/829143 , https://crbug.com/770889

Convert field_gen() and field_val() into macros (here clang can
perform the constness check) and call the inline functions
__field_gen() and __field_val() from there.

This is the same approach taken by an upstream driver with the
same problem: 4e59532541c8 ("nfp: don't depend on compiler
constant propagation")

Change-Id: I61198d00db3c5f632cb6274d0f60f1d0cb61872b
Signed-off-by: Matthias Kaehlcke <mka@chromium.org>